### ISSUE TITLE
How can I trigger it on the branch of the PR?

### ISSUE THREAD

**Issue by dunklesToast** [peter-evans/slash-command-dispatch#100]
Hi,

I'm trying to implement a custom workflow which runs on the branch of the PR where the command was triggered.

My trigger looks like this:

```yml
name: Dispatcher
on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          allow-edits: true
          reaction-token: ${{ secrets.REPO_PAT }}
          permission: write
          dispatch-type: workflow
          ref: ${{ env.GITHUB_REF }}
          commands: |
            test
```

If I write `/test` in my PR it'll trigger the dispatcher and also the action which listens on the Event but it will alway use the main branch. Is there a way to use the PR branch? As you can see I tried using the `ref` argument but thats not recognized.

My custom action to be triggered looks like this:
```yml
name: Testing

on:
  workflow_dispatch:

jobs:
  jest:
    name: Run Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
```

I verfied that the commit hash was wrong in the GitHub UI: 
![image](https://user-images.githubusercontent.com/17279485/110311555-3d346300-8004-11eb-8134-c79aa1b34601.png)
This commit is from the main branch and not from my PR:
![image](https://user-images.githubusercontent.com/17279485/110311648-61903f80-8004-11eb-98cc-79ca6c1c081b.png)

Expected behaviour would be, that it checks out the branch which is associated with the Pull Request where I typed the command. Is this even possible?

**Comment by peter-evans** [comment]
Hi @dunklesToast 

It's awkward to do this with `workflow_dispatch` workflows because those events [don't support being able to send a `client_payload`](https://github.com/peter-evans/slash-command-dispatch/blob/master/docs/workflow-dispatch.md#action-behaviour). To make it work with `workflow_dispatch` you would need to send it more information using slash-command parameters. e.g. `/test branch=my-pr-branch`.

I recommend switching your workflow to `repository_dispatch` and remove the `dispatch-type: workflow` line from your configuration. This will enable the action to send the [pull request context](https://github.com/peter-evans/slash-command-dispatch#github-and-pull_request-contexts) with the dispatch request.

I recommend looking at [the demo](https://github.com/peter-evans/slash-command-dispatch/pull/28) to see how to setup your command workflow. The `/black` command executes [this workflow](https://github.com/peter-evans/slash-command-dispatch-processor/blob/master/.github/workflows/black-command.yml). In the workflow you can see [here](https://github.com/peter-evans/slash-command-dispatch-processor/blob/master/.github/workflows/black-command.yml#L13-L14) how it fetches what branch to target from the `client_context`.

**Comment by dunklesToast** [comment]
Okay I found out that GitHub doesn't sync the UI with the branch you actually checkout. UI looks like this
![image](https://user-images.githubusercontent.com/17279485/110482771-4ba87a80-80e9-11eb-811d-0b7853bc6688.png)
The Hash is the newest in the main branch but it does checkout my branch. I guess there is no way to make the Action Results show up under the PR? 

Like this:
![image](https://user-images.githubusercontent.com/17279485/110483643-37b14880-80ea-11eb-951a-1194a6b8d5e8.png)

**Comment by peter-evans** [comment]
Just to back up a bit, how did you resolve your issue to get this working. Did you follow my recommendation? Or you found another way?

To answer your second question, I think it's possible to have a check show up under the PR for the slash command but I've not attempted it myself yet. See [this conversation](https://github.com/peter-evans/slash-command-dispatch/issues/87#issuecomment-712414961) for some sample code.

**Comment by reintroducing** [comment]
I am having what I guess you can call a similar issue. I have a workflow file named `slash-command-dispatch.yml` that looks like this:
```
name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slash-command-dispatch:
    runs-on: selfhosted-fe-platform
    steps:
      - name: Parse Slash Command
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          reaction-token: ${{ secrets.GH_TOKEN }}
          config: >
            [
              {
                "command": "canary",
                "permission": "none",
                "issue_type": "pull-request"
              }
            ]
```

I then have a `canary-command.yml` file that should be getting called when I comment `/canary` in a PR, but it does not seem to be firing at all:
```
name: canary-command

on:
  repository_dispatch:
    types: [canary-command]

jobs:
  canary:
    runs-on: selfhosted-fe-platform
    env:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
    steps:
      - name: Check out repo
        uses: actions/checkout@master
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm ci
      - name: Create npm package output
        run: npm run build
      - name: Create canary release
        run: npx auto canary
```

What am I missing here?
