### ISSUE TITLE
Send sha of PR via static-args

### ISSUE THREAD

**Issue by esvirskiy** [peter-evans/slash-command-dispatch#121]
Hi.

I am trying to send an argument using the PR's sha but it's showing up as empty.

Here's my code:

```
name: slash-command-dispatch

on:
  issue_comment:
    types: [created]

jobs:
  chatops:
    runs-on: ubuntu-latest
    steps:
      - name: Do stuff
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          issue-type: pull-request
          dispatch-type: workflow
          permission: none
          commands: |
            continuous-delivery
          repository: my/repo
          static-args: |
            sha="${{ github.event.pull_request.head.sha }}"
```

Thanks!
