### ISSUE TITLE
create-or-update-comment does not dispatch slash commands

### ISSUE THREAD

**Issue by pauleustice** [peter-evans/slash-command-dispatch#125]
Firstly, I'd like to say thank you for releasing such a useful tool and with great documentation too!

I have a few fairly complex slash command workflows and would like one of my jobs to trigger a subsequent one that uploads the first one's run artifacts. I have a step like this:

```
- name: 'Start attaching artefacts'
   uses: ./github/actions/peter-evans-create-or-update-comment
   with:
     token: ${{ secrets.GITHUB_TOKEN }}
     repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
     issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
     body: /attach-artifacts someArgumentsHere
```

Unfortunately, the comment that's generated doesn't trigger the workflow as expected. Manually typing it will. Is there a way to make this work?

I would just combine the two, but artifacts aren't available through the API until the job has completed, so they must be accessed in a secondary workflow.
