### ISSUE TITLE
Checking out the correct branch

### ISSUE THREAD

**Issue by roderik** [peter-evans/slash-command-dispatch#133]
We checkout the PR commit with

```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0
```

and we use the automated docker image tagging from docker to tag our containers. But for some reason it detects our main branch, not the pr branch.

Is there a way to actually checkout the right branch?
