### ISSUE TITLE
Unable to access token.

### ISSUE THREAD

**Issue by teezzan** [peter-evans/slash-command-dispatch#134]
Hello, Thanks for the good work.
I was setting up a basic workflow and I came across an error that states `Error: Missing required input 'token'.`. This error is popping up even though I have `secrets.PAT` set up for the project. 
My code is as follows.
```yaml
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          commands: |
            deploy
            integration-test
            build-docs

``` 
The complete error logs are as follows.

```bash
Run peter-evans/slash-command-dispatch@v2
  with:
    issue-type: pull-request
    commands: format-pr
  
    reaction-token: ***
    reactions: true
    permission: write
    allow-edits: false
    repository: teezzan/Quarto
    event-type-suffix: -command
    dispatch-type: repository
Error: Missing required input 'token'.
```
What am I doing wrong?
Thanks
