### ISSUE TITLE
Slash Command Triggers event, not reporting to pull request

### ISSUE THREAD

**Issue by ematta** [peter-evans/slash-command-dispatch#141]
The slash command dispatch for the test execution works as expected, however, it does not report status back to the pull request it was triggered from. When I run `/test` dispatch works and the tests execute. Is this an issue or have I implemented this incorrectly?

```yaml
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.PAT }}
          commands: |
            test
          permission: write
          issue-type: pull-request
          reactions: true
          allow-edits: true

```

```yaml
name: CI testing

on:
  push:
    branches:
      - 'master'
  repository_dispatch:
    types: [test-command]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.pull_request.draft == false }} || ${{ github.event.client_payload.slash_command }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.8]
        requires: ['oldest', 'latest']
    timeout-minutes: 35

    steps:
    - name: Checkout Code (Slash Command Only)
      if: ${{ github.event.client_payload.slash_command }}
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
        ref: ${{ github.event.client_payload.pull_request.head.ref }}
        fetch-depth: "5" # For codecov

    - name: Checkout Code
      if: ${{ !github.event.client_payload.slash_command }}
      uses: actions/checkout@v3
      with:
        fetch-depth: "5" # For codecov

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt --quiet
      shell: bash

    - name: Tests
      run: |
        pytest tests
```
