### ISSUE TITLE
Command not triggered

### ISSUE THREAD

**Issue by pmpinto** [peter-evans/slash-command-dispatch#143]
Hey! 👋 
It's perhaps a bit too late on a Friday, but I feel like I have everything as it's supposed to, but I'm still not seeing any action.

So, I'm on a private test repo, where I have created a `SLASH_COMMANDS_TOKEN` PAT.
Then, I have the following files (both on `master` and `test-branch`):

`.github/workflows/slash-commands.yml`
```yml
name: Slash Command Dispatch

on:
  issue_comment:
    types:
      - created

jobs:
  slashCommandDispatch:
    name: Dispatch command
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        name: Slash Command Dispatch
        with:
          token: ${{ secrets.SLASH_COMMANDS_TOKEN }}
          commands: |
            hello-world
          permission: none
          issue-type: pull-request
```

`.github/workflows/hello-world-command.yml`
```yml
name: Hello World Command

on:
  repository_dispatch:
    types: [hello-world-command]
    
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            [Click here to see the command run output][1]
            [1]: ${{ steps.vars.outputs.run-url }}
```

---

That's my setup!

Now with that setup my expectation is that when I create a comment on pull request starting with `/hello-world`, slash commands would pick it up and dispatch an event that would kick in whatever is defined under `hello-world-command`.

But what really happens is… absolutely nothing!

So what's that obvious thing I'm clearly missing? 🙈 
Thanks!
