### ISSUE TITLE
Can GITHUB_TOKEN be used in place of PAT (github update)

### ISSUE THREAD

**Issue by dhruvCW** [peter-evans/slash-command-dispatch#147]
Hi love this action 🍻 

based on this post from github https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/

I was wondering does this mean its possible to use this action entirely with just the `GITHUB_TOKEN` secret and no longer require a PAT ?

**Comment by dhruvCW** [comment]
spoiler alert it seems it does work as expected 👍

**Comment by peter-evans** [comment]
Hi @dhruvCW 

I saw that blog post, too. Thank you for testing it!

I've not had chance to test it myself yet, but my guess is that there are still situations where you might need a PAT. For example, if the dispatch is to a remote repository, not the local one associated with the `GITHUB_TOKEN`. So there are a few things I want to test before updating documentation, or even the action itself.

**Comment by rijkvanzanten** [comment]
Heya! Just wanted to chime in here and also confirm that it seems to work as expected with a `GITHUB_TOKEN` as long as your workflow is on the _current repo_ (private or public) 🚀

**Comment by terrabitz** [comment]
Just to throw my 2 cents here, I found that I was able to run using the `GITHUB_TOKEN`, but it needed a couple extra permissions to do so:

```
permissions:
  pull-requests: write  # For doing the emoji reaction on a PR comment
  issues: write  # For doing the emoji reaction on an issue comment
  contents: write  # For executing the repository_dispatch event
```

This will only work for the local repository though. If you want to call a remote repo, you have to use a classic PAT. (The new fine-grained PATs won't work until [GitHub adds support for them in the GraphQL API](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql))
