### ISSUE TITLE
Allow running commands within comment workflow

### ISSUE THREAD

**Issue by danielrbradley** [peter-evans/slash-command-dispatch#188]
The drawback as noted by using either command or workflow dispatch is that it won't automatically report the status back to the originating pull request. If the workflow actually runs within the original comment workflow it should automatically report its status to the pull request.

What I'd propose is:
1. Adding a third option to `dispatch-type` of something like `none` or `synchronous` to indicate that no dispatch will be triggered by the action.
2. Adding an output of `command` which is returned identifying which command was matched. This would be empty if unmatched or authorisation failed.

This would allow the action to be optionally be used as such:

```yaml
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command
        id: slash-command
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: |
            deploy
          dispatch-type: none

      - name: Deploy
        if: steps.slash-command.outputs.command == 'deploy'
        uses: ./.github/actions/deploy
```
