### ISSUE TITLE
Question: Getting output of command dispatch

### ISSUE THREAD

**Issue by stack72** [peter-evans/slash-command-dispatch#29]
Hi,

Thanks so much for all of the work regarding this command dispatch work. I have successfully been able to send command dispatch processes to my processor repo as per https://peterevans.dev/posts/chatops-for-github-actions/

One question - repo A dispatches the command to repo B, is there any way that repo A can be updated with the link to the repo B action so we can link the results?

Thanks again

Paul

**Comment by peter-evans** [comment]
Hi Paul,

If you have followed the guide in that blog post then you should have a command workflow that uses the [create-or-update-comment](https://github.com/peter-evans/create-or-update-comment) action to set a reaction on the original comment. You can also use that same action to reply with a new comment, or edit the original comment. See [these examples](https://github.com/peter-evans/create-or-update-comment#add-a-comment-to-an-issue-or-pull-request).

I'm not sure if it's possible to get the link to the workflow run results. I know that there are [two new environment variables](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables), `GITHUB_RUN_ID` and `GITHUB_RUN_NUMBER`. One of those might be the same run ID that appears in the URL for the action results. In which case, it could be returned in a new comment as I mentioned above.

**Comment by peter-evans** [comment]
I just did a quick test and confirmed that `GITHUB_RUN_ID` is the correct one to get the URL.

Try this to reply with a new comment containing the link to the results.
```
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            [Command results][1]

            [1]: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
```
