### ISSUE TITLE
"Warning: Failed to set reaction on comment ID xx."

### ISSUE THREAD

**Issue by clxmstaab** [peter-evans/slash-command-dispatch#376]
we get a error message after sending a comment with this workflow:

```
# DONT EDIT THIS FILE OUTSIDE OF complex-gmbh/php-automation-templates
# changes will be one-way synced from the automation repos

name: Chatops

on:
  issue_comment:
    types: [ created ]

jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PHP_GH_ACTION }}
          # reactions should be reported from github itself
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: help, csfix, phpstan-baseline, deptrac-baseline, merge, ghostinspector, set-pr-description
          issue-type: pull-request
```

we warning the error "Warning: Failed to set reaction on comment ID xx." only for the `/set-pr-description` command.
the other chat commands in the same workflow work.

looking at the sources I can see only a single `catch` block which logs this warning
https://github.com/peter-evans/slash-command-dispatch/blob/31da94ea5fd5cf7ec11607d4c9cd21df9a326871/src/github-helper.ts#L106-L107

to ease debugging our problem it would be helpful to see the actual exception the octokit returns in this case.
is there a way to load the `slash-command-dispatch` action into our workflow with debug logging enabled?
