### ISSUE TITLE
Not returning the context `client_payload`

### ISSUE THREAD

**Issue by awmatheson** [peter-evans/slash-command-dispatch#38]
Hi @peter-evans, thanks for building this action! 

This could be my misunderstanding, but I am having trouble accessing the context of the to return the named args in the way specified in the docs. When I run the example [here](https://github.com/peter-evans/slash-command-dispatch#github-and-pull_request-contexts) I get null returned. 

Here is the code I am using:

```yaml
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1.1.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: deploy
          reaction-type: hooray
          permission: write
          issue-type: pull-request
          named-args: true
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
```

And the command I am using to trigger: `/deploy profile=true dev=true`

The output of the action is:
```
Run echo "$PAYLOAD_CONTEXT"
  echo "$PAYLOAD_CONTEXT"
  shell: /bin/bash -e {0}
  env:
    PAYLOAD_CONTEXT: null
null
```

The `REPO_ACCESS_TOKEN` has the scope set to repo (all) and admin:repo_hook (all).

I made a toy repo to try and debug this. It is public - https://github.com/awmatheson/kelastic/pulls

Thanks in advance for your help! 🙇

**Comment by peter-evans** [comment]
Hi @awmatheson 

There are two workflows you need to make this work. The first is the one you already have, which triggers on `issue_comment` events. This will "listen" for slash commands in comments and when it finds one that matches your configuration it will create a `repository_dispatch` event with a payload containing the slash command details.

In order to handle that event and do something when the command is issued, you need another workflow. It will look something like this:
```
name: Deploy Command
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  deployCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
```

Hope that helps. There is also a [Getting started](https://github.com/peter-evans/slash-command-dispatch/blob/master/docs/getting-started.md) tutorial that walks you through the setup.
