### ISSUE TITLE
local slash commands

### ISSUE THREAD

**Issue by staabm** [peter-evans/slash-command-dispatch#40]
Does this workflow also support local slash commands?

We dont want to configure a distributed system and instead have everything inside each repo, but use the slash command logic and workflow execution...

Is this a supported scenario?

**Comment by staabm** [comment]
Ohh I guess this is what I need:
https://github.com/peter-evans/slash-command-dispatch/blob/master/.github/workflows/hello-world-command.yml

**Comment by peter-evans** [comment]
Yes, it is supported. It's actually the default because the `repository` action input defaults to the current repository. So just put the `repository_dispatch` workflow in the same repo as the `issue_comment` workflow.

**Comment by staabm** [comment]
Really cool, thx. I guess this is something which should be mentioned in the readme, because when reading it one gets the impression that the async dispatched command is the only and primary use-case

**Comment by peter-evans** [comment]
Put a note in the README here to try and make it more clear.
https://github.com/peter-evans/slash-command-dispatch#standard-configuration

Thanks!

**Comment by staabm** [comment]
thx, thats awesome.

I am trying to build a local command workflow, which is able to determine within the locally dispatched job, that it was triggered by a slash command.

it doesn't work though.. couldn't find a example which does the same thing in the reposes.

my workflow is triggerd, but the condition steps get skipped instead of beeing executed:
```
name: php-cs-fixer

on:
  push:
  repository_dispatch:
    types: [csfix-command]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.STAABM_TOKEN }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.0

    - run: |
        composer install --prefer-dist --no-progress --no-scripts --no-suggest # install the apps dependencies
        composer bin php-cs-fixer install --no-progress

    - run: composer csfix # auto-fix
      if: "github.event.client_payload.slash_command"

    - name: Commit changed files
      if: "github.event.client_payload.slash_command"
      uses: stefanzweifel/git-auto-commit-action@v4.0.0
      with:
        commit_message: Apply php-cs-fixer changes

```


debugging with 
```
    - run: echo "Hello ${{ github.event.client_payload.slash_command }}!"
    - run: echo "Hello ${{ github.event.client_payload.slash_command.command }}!"
```

reveled that `github.event.client_payload.slash_command` is empty?

**Comment by staabm** [comment]
hmm like reported in https://github.com/peter-evans/slash-command-dispatch/issues/38 my `client_payload` is null.. investigation in progress..

**Comment by staabm** [comment]
ok.. I guess my problem was/is, that I tested the feature in a PR, but the `issue_comment` workflow need to be merged into `master` for testing

**Comment by staabm** [comment]
using `if: "github.event_name == 'repository_dispatch'"` for now.. maybe its a problem because we use a private repo

**Comment by staabm** [comment]
more investigation.. in the `repository_dispatch` event we need to explicitly declar `repository` and `ref` for `actions/checkout@v2`, even when local-repo-dispatching

```
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
```
