### ISSUE TITLE
Add conditional job documentation

### ISSUE THREAD

**Issue by lukasz-mitka** [peter-evans/slash-command-dispatch#400]
Please add documentation and examples for avoiding running jobs when comment is not in fact a 'slash command'.

`if: startswith(github.event.comment.body, '/')` appears to be a good way to do so. As in
```yaml
jobs:
  slashCommandDispatch:
    if: startswith(github.event.comment.body, '/')
```

By avoiding running jobs it's possible to lower te bill on 'comment heavy' repos.
