### ISSUE TITLE
Feature Request: Add opener permission

### ISSUE THREAD

**Issue by AustinShalit** [peter-evans/slash-command-dispatch#66]
I am looking into creating a slash command to run a code formatter and auto commit the diff to a PR from a fork. I was going to set the permission on the dispatch to be `write` that way all repo collaborators could run the command. However, it would be cool if the folks with write permission on the fork could run the command too. As an example, take a look at this test PR:

https://github.com/AustinShalit/actions-test/pull/4

I would've liked both `/format` requests to be run. Any advice on how to accomplish this?

**Comment by peter-evans** [comment]
Hi @AustinShalit 

Interesting feature idea! Unfortunately, I don't think it's possible to allow slash command execute permission for _all_ users with `write` access to the fork. The reason for this is that the auth token the action holds doesn't permit the API call to check the permissions of collaborators on the fork.

I have two alternatives, both of which could be useful to users of this action:

1. Add a feature to allow the user that authored the pull request to execute commands. This is easy to implement because the author of the PR is openly available to the repository it's opened in. It means it's limited to just one collaborator of the fork, the PR author, but it would have allowed your example to work.
2. Add a feature to configure a list of users that have permission to execute a command regardless of their role.

The second option might look something like the following two examples.

Basic configuration (applied to all commands)
```
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          issue-type: pull-request
          commands: format
          users: |
            ItayZiv
            collaborator2
            collaborator3
```

Advanced configuration (applied to just the `format` command)
```
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          config: >
            [
              {
                "command": "format",
                "issue_type": "pull-request",
                "users": [ "ItayZiv", "collaborator2", "collaborator3" ]
              }
            ]
```

Let me know what you think about these proposed features.
