### ISSUE TITLE
Slash commands broken when opening PR for non-master branch

### ISSUE THREAD

**Issue by wildlifehexagon** [peter-evans/slash-command-dispatch#76]
I'm attempting to run this action locally using the same example from the documentation. However, when I execute a slash command inside a pull request that is merging `feature/xyz` into `develop` (i.e. a non-master branch), the dispatch action breaks entirely.

Here's my dispatch workflow

```yaml
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch slash command (example)
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          issue-type: pull-request
          commands: example
```

and the example command workflow

```yaml
name: Slash Command Processor (Example)
on:
  repository_dispatch:
    types: [example-command]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
```

The error I get from the first action (after leaving a slash command comment in the PR) is this:

```
Using configuration from yaml inputs.
Command 'example' to be dispatched.
##[error]Cannot read property 'slice' of null
```

Is it possible to use this action when merging into a non-master branch?
