### ISSUE TITLE
output parameter: url to the pull request, in which a slash command was issued

### ISSUE THREAD

**Issue by clxmstaab** [peter-evans/slash-command-dispatch#81]
would be great there would be some kind of variable/output parameter which contains a url to the pull request in which the chatops command was triggered (when inside the action which is triggered by the chatops command).

this url could then be used in combination with https://github.com/peter-evans/create-pull-request to post this url into the pull request body and therefore make github.com link the triggering comment with the newly created pull request

note: this is **not** the very same request as in https://github.com/peter-evans/create-pull-request/issues/579 (or a duplicate)

**Comment by peter-evans** [comment]
Hi @clxmstaab 

This is available in the `pull_request` context.

`github.event.client_payload.pull_request.html_url`
e.g. `https://github.com/peter-evans/slash-command-dispatch/pull/2`

Or

`github.event.client_payload.pull_request.url`
e.g. `https://api.github.com/repos/peter-evans/slash-command-dispatch/pulls/2`

You can check all the available context parameters by dumping them in the `repository_dispatch` workflow.

```yml
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
```
