### ISSUE TITLE
Sending a commit ref as part of the command dispatch

### ISSUE THREAD

**Issue by stack72** [peter-evans/slash-command-dispatch#89]
Hi @peter-evans 

Can you tell me if there is a way to be able to send a ref as part of the data for the command dispatch? I am currently trying to use this for community based workflows for PRs

But when I trigger the command dispatch, it's triggering it from the latest main repo rather than for a specific ref

Thoughts here would be great

Paul

**Comment by peter-evans** [comment]
Hi Paul,

The action sends contexts with the dispatch. See the docs [here](https://github.com/peter-evans/slash-command-dispatch#github-and-pull_request-contexts). If you send a command from a pull request the `github.event.client_payload.pull_request` context will contain ref details for the pull request.

If that doesn't fit your use case then the alternative is to send a command argument with the information you want.

For example, you can ask users to specify a ref when executing the command.
```
/my-command ref=develop
```

Alternatively, if the ref is static, or you can determine the ref when the `issue_comment` workflow executes then you can use the `static-args` input to set the ref so the users don't need to specify when they issue the command.
```yml
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          commands: |
            my-command
          static-args: |
            ref=develop
```
