### ISSUE TITLE
Command is not configured for the issue type 'pull request'

### ISSUE THREAD

**Issue by ARogovsky** [peter-evans/slash-command-dispatch#92]
Hi
This is my action for a chatbot in PR:
```

name: "Echo bot v2"
on:
  issue_comment:
    types: [created]
jobs:
 ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        token: ${{ secrets.PAT }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Chat
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          permission: none
          issue-type: issue
          commands: |
            ping

```

When I try to execute it, I got this message:

```
Run peter-evans/slash-command-dispatch@v2
  with:
    token: ***
    reaction-token: ***
    permission: none
    issue-type: issue
    commands: ping
  
    reactions: true
    allow-edits: false
    repository: ARogovsky/InfraSec
    event-type-suffix: -command
    dispatch-type: repository
Using configuration from yaml inputs.
Command 'ping' is not configured for the issue type 'pull request'.

```
