### ISSUE TITLE
Unexpected inputs provided but inputs are configured in workflow

### ISSUE THREAD

**Issue by andrew-devops** [peter-evans/slash-command-dispatch#95]
Hi!

I have a chatops flow. The chatops flow is use peter-evans/slash-command-dispatch@v2 for call workflows from pull requests:
```
name: "Chat bot v2"
on:
  issue_comment:
    types: [created]
jobs:
 comment-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Chat
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          dispatch-type: workflow
          commands: |
            help
            deploy
            deploy-env
            destroy
            checkme
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}

```

Also I have workflow named deploy-env-command.yml:

```
name: "Deploy envirovment workflow"
on:
  workflow_dispatch:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
jobs:
  setup-env-v2:
    runs-on: ubuntu-latest
    steps:

```

The issue is strange message in action flow:

```
Run peter-evans/slash-command-dispatch@v2
Using configuration from yaml inputs.
Command 'deploy-env' to be dispatched.
Error: Unexpected inputs provided: ["repository", "comment-id"]
```

Can you explain why I get this error? I was configured inputs for workflow.
