### ISSUE TITLE
[DOUBTS] How to supply an input to a workflow where input depends on what the wokflow produces.

### ISSUE THREAD

**Issue by forkbabu** [peter-evans/slash-command-dispatch#96]
- Workflow produces a URL that I need to go to
- the URL website produces a response that I need to copy paste into the user input field (stdin)
- Maybe this prev step can be done by creating an issue or PR and do chatops. I am new to this repo.
- I'm using python btw.
- The workflow continues to work normally and pastes a output string into an existing comment on an issue or PR. 

@peter-evans can u help me understand what to do here?

**Comment by peter-evans** [comment]
@forkbabu I'm sorry but I don't understand what you are trying to do. I think you need to explain in a lot more detail and preferably provide some workflow example of what you have tried already.

**Comment by forkbabu** [comment]
@peter-evans thanks for the speedy reply. I am new to both Github Actions and ChatOps.
I'm trying to create a Spotify playlist recommendation system using Github Actions.
More on this is given [here](https://github.com/forkbabu/ucalyptus-recsys/blob/main/.github/workflows/cml.yaml)

## Normally when this is not part of CI/CD workflows
Normally, `recsys.py` asks the user to paste a token into the user input field.
Now the token is obtained by the user when he clicks a URL that recsys.py provides
In other words, Oauth2 is being done here. More code details on this is [here](https://github.com/forkbabu/spotipy/blob/cml/spotipy/oauth2.py#L378)

## But using this python file inside a workflow

The problem surely arises when I want to do the user_input.
### [Proof that it fails because of that](https://github.com/forkbabu/ucalyptus-recsys/runs/1866010344?check_suite_focus=true)

## So my Question 
Can chatops solve this problem? If no, do you have a simpler workaround for this.

```
name: recommend-a-playlist

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Machine Learning
      env:
        SIMONW_TOKEN: ${{ secrets.FORKBABU_TOKEN }}
        SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USERNAME: ${{ secrets.USERNAME }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      run: |-
        python3 recsys.py
```
