### ISSUE TITLE
 [HELP] using Workflow_dispatch type to tie run with branch/pr.

### ISSUE THREAD

**Issue by jay2610** [peter-evans/slash-command-dispatch#97]
First, Loved your work on this, definitely want to use this. 

Challenges I'm facing right now are
1.  to add ref with workflow_dispatch type to reflect associated branch with that action run.
2. Have PR checks for that action run triggered by workflow_dispatch run (Not sure if fixing ref for my branch with have github checks as well with that PR.)

I tried adding ref to workflow_dispatch input 
``` 
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      issue-number:
        description: 'The issue number in which the slash command was made'
        required: true
      actor:
        description: 'The user who executed the slash command'
        required: true
      ref:
        description: 'Github REF'
        required: true
```
But it returns `Required input 'ref' not provided` 

This is my dispatch workflow 

```
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.GIT_ACTION_SECRET }}
          reactions: seen
          dispatch-type: workflow
          commands: |
            runways
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            issue-number=${{ github.event.issue.number }}
            actor=${{ github.actor }}
            ref=${{github.ref}}
 ```
 
 Thanks again for your awesome work!
